Feature/lp 29 forgot password
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #16
Opened 2021-02-03 20:56 UTC by javier1martinez

- Forgot password feature.
- Added link to forgot password page.
- forgot password page will send an email with a link to the email in the system.
- reset password page will allow creating a new password.

2021-02-03 22:12 UTC, YogirajA requested changes

2021-02-03 22:12 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Controllers/AccountController.cs
> +                var callback = new System.Uri(Microsoft.AspNetCore.WebUtilities.QueryHelpers.AddQueryString("http://" + Request.Host.Host + "/Account/ResetPassword", param)).ToString();
same as above.

2021-02-03 22:12 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Controllers/AccountController.cs
> +            catch(System.Exception ex)
We don't need to try/catch explicitly. We have `ApiExceptionFilter ` to handle this. Please check other actions for the usage pattern.

2021-02-03 22:12 UTC, YogirajA commented on src/API/LeadershipProfileAPI/EmailService/EmailSender.cs
> +    public class EmailSender : IEmailSender
Why is this class required? We already have `SmptSender`. Please use that instead.

2021-02-03 22:12 UTC, YogirajA commented on src/API/LeadershipProfileAPI/EmailService/IEmailSender.cs
> +    public interface IEmailSender
No need for this.

2021-02-03 22:12 UTC, YogirajA commented on src/Web/src/components/LoginComponents/UseForgotPassword.js
> +			const apiUrl = new URL(`https://localhost:5001/account/forgotPassword`);
This comes from `Config` object. Please don't hardcode the address like this. Check other endpoints for patterns.

2021-02-03 22:12 UTC, YogirajA commented on src/Web/src/components/LoginComponents/UseResetPassword.js
> +			const apiUrl = new URL(`https://localhost:5001/account/resetPassword`);
same as above.

2021-02-03 22:12 UTC, YogirajA commented on src/API/LeadershipProfileAPI/EmailService/EmailConfiguration.cs
> +    public class EmailConfiguration
This is not required.

2021-02-03 22:39 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/ForgotPassword.js
> +		e.preventDefault();
make sure the indentation is the same

2021-02-03 22:40 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/ForgotPassword.js
> +				{/* <Input type="button" value="Go Back" className="login-submit" onClick={e => handleOnClick(e)}/> */}
does the commented out code need to be here?

2021-02-03 22:42 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/ResetPassword.js
> +    };
make sure indentation is the same as line 8

2021-02-03 22:42 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseForgotPassword.js
> +	const [username, setUsername] = useState('');
indentation

2021-02-03 22:46 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseForgotPassword.js
> +					setTimeout( () => {history.push('/account/Login'); history.go(0);}, 3000);
indentation and extra space between parentheses

2021-02-03 22:46 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseLogin.js
> +		goToForgotPassword,
indentation

2021-02-03 22:47 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/Login.js
> +		e.preventDefault();
indentation

2021-02-03 22:48 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/Login.js
> +                <a href="#"className="login-submit" onClick={e => handleOnClick(e)}>Forgot Password?</a>
inconsistent spacing

2021-02-03 22:49 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseForgotPassword.js
> +	function goToLogIn() {
the functions seem to be indented in more than the consts above

2021-02-03 22:50 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseForgotPassword.js
> +		goToLogIn,
indentation

2021-02-03 22:50 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseLogin.js
> +		let path = '/account/ForgotPassword';
lines 28-30 seem to have more indentation than the function below

2021-02-03 22:50 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseResetPassword.js
> +	const history = useHistory();
indentation

2021-02-03 22:51 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseResetPassword.js
> +					setTimeout( () => {history.push('/account/Login'); history.go(0);}, 3000);
indentation and space between parentheses

2021-02-03 22:51 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseResetPassword.js
> +		error,
indentation

2021-02-03 22:52 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseResetPassword.js
> +		setResetPassword,
indentation

2021-02-03 22:53 UTC, allisono-hs commented on src/Web/src/components/LoginComponents/UseForgotPassword.js
> +			fetch(apiUrl, {
indentation

2021-02-04 00:10 UTC, javier1martinez reviewed
Comments reviewed and fixed

2021-02-04 02:25 UTC, YogirajA requested changes

2021-02-04 02:25 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Controllers/AccountController.cs
> +        public async Task<ForgotPasswordResultModel> RorgotPasswordAsync(ForgotPasswordModel model)
Fix the typo

2021-02-04 02:25 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Startup.cs
> +            opt.TokenLifespan = TimeSpan.FromHours(7));
This should be coming from an environment variable.

2021-02-04 02:25 UTC, YogirajA commented on src/Web/src/components/LoginComponents/UseResetPassword.js
> +                headers: {
All of this is `API_CONFIG`. Please use that instead of recreating all the config.  Look at `setLogin` for pattern

2021-02-05 15:13 UTC, YogirajA approved these changes

2021-02-05 16:41 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Exchange-OSS/Leadership-Profile?pullRequest=16) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Exchange-OSS/Leadership-Profile?pullRequest=16) before we can accept your contribution.<br/>**0** out of **4** committers have signed the CLA.<br/><br/>:x: YogirajA<br/>:x: javierg85<br/>:x: allisono-hs<br/>:x: javier1martinez<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Exchange-OSS/Leadership-Profile?pullRequest=16) it.</sub>

2021-02-05 17:34 UTC, YogirajA requested changes
@javier1martinez  We are bringing in some old commits. Please rebase main and resolve this. Also, please make sure all the commits are signed.

2021-02-08 21:49 UTC, YogirajA commented
PR from feature/LP-29-ForgotPassword3 branch is merged. Closing this PR.

2021-02-08 21:49 UTC, closed without merging