Implemented sorting for profile list endpoint
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #17
Opened 2021-02-05 15:30 UTC by harveymw27

Added Id to ProfileList for future development need.

Created extension method for IQueryable to process 1 to N 'ThenBy' calls.

Added logic to handle sorting requests from the profile endpoint.

Added tests for sorting

2021-02-05 15:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Ed-Fi-Exchange-OSS/Leadership-Profile?pullRequest=17) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Ed-Fi-Exchange-OSS/Leadership-Profile?pullRequest=17) before we can accept your contribution.<br/><hr/>**Mark Harvey** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Ed-Fi-Exchange-OSS/Leadership-Profile?pullRequest=17) it.</sub>

2021-02-08 22:52 UTC, YogirajA requested changes

2021-02-08 22:52 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Features/Profile/List.cs
> +                List<Expression<Func<ProfileList, object>>> orderByExpressions = new();
can we refactor switch statement here? We could replace something more readable like 
```
 var dict = new Dictionary<string, Expression<Func<ProfileList, object>>> { { "id", o => o.StaffUniqueId } };
   query = query.OrderBy(dict[request.SortField]);
```

2021-02-08 22:52 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Extensions/IQueryableExtensions.cs
> +        public static IOrderedQueryable<T> OrderBy<T>(this IQueryable<T> queryable, List<Expression<Func<T, object>>> orderByExpressions)
Let's rename this so that we know we are using a custom implementation and not the default one.

2021-02-08 22:52 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Extensions/IQueryableExtensions.cs
> +        public static IOrderedQueryable<T> OrderByDescending<T>(this IQueryable<T> queryable, List<Expression<Func<T, object>>> orderByExpressions)
same as above

2021-02-08 22:52 UTC, YogirajA commented on src/Web/src/components/DirectoryComponents/TableList.js
> +                    {data !== [] ?
looks like an unnecessary spacing change. Can we back this out?

2021-02-10 17:13 UTC, harveymw27 commented on src/API/LeadershipProfileAPI/Features/Profile/List.cs
> +                List<Expression<Func<ProfileList, object>>> orderByExpressions = new();
I'm not sure this solution handles complex needs of sorting. When we need to sort by multiple fields, we can not initialize the container in this manner as it only allows for one property to be added per "field."

Do it that way might look something like:

                var dict = new Dictionary<string, Expression<Func<ProfileList, object>>>
                {
                    { "id", o => o.StaffUniqueId },
                    { "name", o => o.LastSurName }, // We cannot add the first name here
                    { "location",  o => o.Location }
                    /// etc
                };

But we would really need to it look like:

                var dict = new Dictionary<string, List<Expression<Func<ProfileList, object>>>>
                {
                    { "id", new List<Expression<Func<ProfileList, object>>> { o => o.StaffUniqueId } },
                    { "name",  new List<Expression<Func<ProfileList, object>>>  {o => o.LastSurName, o => o.FirstName} },
                    { "location",  new List<Expression<Func<ProfileList, object>>> { o => o.Location } }
                    /// etc
                };

It would also create more complexity with default sorting of string fields with null values (which I'm not sure how we would accomplish this because we would need to unbox the expression to get to the property itself).

It might be something like:

                if (isAscending)
                {
                    var expression = dict[request.SortField].FirstOrDefault();
                    var method = expression.Compile();
                    var obj = method(GetTheResultObjectThroughReflectionOrSomething);
                    var objType = obj.GetType();

                    if (objType is string)
                    {
                        query = query.OrderBy(o => string.IsNullOrEmpty(obj));
                    }
                }

Do we want to head down this path? Do you have something else in mind or maybe something I am not seeing?

2021-02-10 17:16 UTC, harveymw27 commented on src/API/LeadershipProfileAPI/Extensions/IQueryableExtensions.cs
> +        public static IOrderedQueryable<T> OrderBy<T>(this IQueryable<T> queryable, List<Expression<Func<T, object>>> orderByExpressions)
I intended this to be an overload not a default. What name would you like me to use?

2021-02-10 17:16 UTC, harveymw27 commented on src/API/LeadershipProfileAPI/Extensions/IQueryableExtensions.cs
> +        public static IOrderedQueryable<T> OrderByDescending<T>(this IQueryable<T> queryable, List<Expression<Func<T, object>>> orderByExpressions)
I intended this to be an overload not a default. What name would you like me to use?

2021-02-10 17:25 UTC, harveymw27 commented on src/Web/src/components/DirectoryComponents/TableList.js
> +                    {data !== [] ?
Not sure I follow. Do you mean the formatting? There is a change to the 'key' attribute in the TR, but I have formatted the document to look like this:

![image](https://user-images.githubusercontent.com/42792719/107546919-211ade80-6b8a-11eb-9cf0-03160fe8a4ce.png)

2021-02-10 20:35 UTC, harveymw27 commented on src/API/LeadershipProfileAPI/Features/Profile/List.cs
> +                List<Expression<Func<ProfileList, object>>> orderByExpressions = new();
I can't find a way to justify a new method nor a new class. Here is what the dictionary will look like if we implement this:

                var expressionList = new Dictionary<string, List<Expression<Func<ProfileList, object>>>>
                {
                    { "id", new List<Expression<Func<ProfileList, object>>> { o => o.StaffUniqueId } },
                    { "name",  new List<Expression<Func<ProfileList, object>>> { o => o.LastSurName, o => o.FirstName } },
                    { "location",  new List<Expression<Func<ProfileList, object>>> { isAscending? o => string.IsNullOrEmpty(o.Location) : null, o => o.Location } },
                    { "school",  new List<Expression<Func<ProfileList, object>>> { isAscending ? o => string.IsNullOrEmpty(o.Institution) : null, o => o.Institution } },
                    { "position",  new List<Expression<Func<ProfileList, object>>> { isAscending ? o => string.IsNullOrEmpty(o.Position) : null, o => o.Position } },
                    { "yearsOfService",  new List<Expression<Func<ProfileList, object>>> { o => o.YearsOfService } },
                    { "highestDegree",  new List<Expression<Func<ProfileList, object>>> { isAscending ? o => string.IsNullOrEmpty(o.HighestDegree) : null, o => o.HighestDegree } },
                    { "major",  new List<Expression<Func<ProfileList, object>>> { isAscending ? o => string.IsNullOrEmpty(o.Major) : null, o => o.Major } }
                };

Below is the method I came up with, instead of all those "new List" calls, but you can see it just converts the params array into a list... So I think we can safely stick with the above dictionary.

Without any logic in the method it seems very unnecessary and just adds more to maintain. Maybe we can do this in the future as the application matures more:

            private List<Expression<Func<ProfileList, object>>> getExpressionList(params Expression<Func<ProfileList, object>>[] expressions)
            {
                return expressions.Select(s => s).Where(o => o != null).ToList();
            }

This implementation over the switch statement seems unnecessary as we are building the dictionary and populating it with a list of expressions for all sortable fields each time sort is called instead of building one expression tree for the sortable field selected.

I am not married to the switch block, but it feels more efficient and easier to maintain than the dictionary approach. What are your thoughts?

2021-02-10 20:40 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Features/Profile/List.cs
> +                List<Expression<Func<ProfileList, object>>> orderByExpressions = new();
If you go the `new Dictionary<string, List<Expression<Func<ProfileList, object>>>>` route, you can use  `o => isAscending && string.IsNullOrEmpty(o.Location),`. In any case,  there is too much happening in one method. We can at least create another method that gets the correct expression based on the sortfield if not a new factory class for this.  If the expressions start to look too complicated, you can also look at the direct SQL route. Constructing queries is a lot easier than dealing with expressions. EF does a good job of caching and securing them as well.  I think when the search feature comes in, it will become even more complicated. I would make sure this is a litter more extensible than modifying the `switch`.

2021-02-10 20:48 UTC, YogirajA requested changes

2021-02-10 20:48 UTC, YogirajA commented on src/Web/src/components/DirectoryComponents/TableList.js
> +                    {data !== [] ?
right. `<tr key={profile.id}>` should be the only change here, right?  I would put the styling and spacing back the way it was and just make sure I make that change one line. In the future, if there is a bug in the area, we know exactly what was changed instead of other extraneous changes.

2021-02-10 21:06 UTC, harveymw27 commented on src/API/LeadershipProfileAPI/Features/Profile/List.cs
> +                List<Expression<Func<ProfileList, object>>> orderByExpressions = new();
Your last comment was after my update. I redacted my old comment so let me your thoughts on the above solution.

2021-02-10 22:48 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Features/Profile/List.cs
> +                List<Expression<Func<ProfileList, object>>> orderByExpressions = new();
Dictionary was just one thought. You can go with a polymorphic route, or SQL building route, or any other route than `switch`

2021-02-12 16:51 UTC, YogirajA approved these changes

2021-02-12 16:57 UTC, merged