Feature/lp 37 refactor account controller
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #20
Opened 2021-02-10 15:23 UTC by harveymw27

Account controller refactored for vertical-slice pattern

2021-02-15 17:13 UTC, YogirajA requested changes
@harveymw27  Registration issue:
If anyone tries to register with a username that already exists, the API correctly doesn't register the user correctly but frontend flow somehow logs them into an existing account anyway. This must be fixed asap. It may have existed before this. This must be fixed on the frontend as well as on the API.

2021-02-16 05:55 UTC, harveymw27 commented on src/API/LeadershipProfileAPI/appsettings.json
> +    "WebApplicationUrl": "https://localhost:5001"
done

2021-02-16 05:55 UTC, harveymw27 commented on src/API/LeadershipProfileAPI/Features/Account/AccountController.cs
> +    public class ForgotPasswordModel
I will do them all then.

2021-02-16 05:57 UTC, harveymw27 commented on src/API/LeadershipProfileAPI/Features/Account/Delete.cs
> +    public class Delete
I was using it for testing. I left it there should users need to be removed. Do you want it removed?

2021-02-16 05:58 UTC, harveymw27 commented on src/API/LeadershiProfileAPI.Tests/Features/AccountTests.cs
> +﻿using LeadershipProfileAPI.Controllers;
done

2021-02-17 17:22 UTC, harveymw27 commented on src/API/LeadershipProfileAPI/Features/Account/Delete.cs
> +    public class Delete
Removed from code base

2021-02-17 17:23 UTC, harveymw27 commented
> @harveymw27 Registration issue:
> If anyone tries to register with a username that already exists, the API correctly doesn't register the user correctly but frontend flow somehow logs them into an existing account anyway. This must be fixed asap. It may have existed before this. This must be fixed on the frontend as well as on the API.

I am creating a defect ticket for this as it did exist

2021-02-17 21:56 UTC, YogirajA approved these changes

2021-02-17 21:56 UTC, merged