LP-67 - Advanced Search.
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #44
Opened 2021-03-23 01:00 UTC by harveymw27

Added models, views, classes, and endpoints  for search dropdownlist controls.

Added model, view, classes, and endpoint for searching based on filters provided by the body of the request.

2021-03-23 21:27 UTC, YogirajA requested changes

2021-03-23 21:27 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Data/EdFiDbContext.cs
> +        public DbSet<StaffSearch> StaffSearch { get; set; }
Can we be consistent with pluralization?

2021-03-23 21:27 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Data/EdFiDbQueryData.cs
> +        public IQueryable<StaffSearch> GetSearchResults(ProfileSearchRequestBody body, string sortBy = "asc", string sortField = "name", int currentPage = 1, int pageSize = 10)
Why isn't body used? Shouldn't those properties be factored into the search?

2021-03-23 21:27 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Features/Search/MappingProfile.cs
> +                .ForMember(d => d.StaffUsi, o => o.MapFrom(x => x.StaffUsi))
redundant as mentioned above

2021-03-23 23:21 UTC, harveymw27 reviewed
Updated

2021-03-25 01:52 UTC, YogirajA requested changes
As a WIP PR, this looks good. We can't merge this in main until it is in a working state.

2021-03-25 01:52 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Data/EdFiDbQueryData.cs
> +            }
We don't have to repeat if/else here. At a very minimum, it could be pushed into an extension method.

2021-03-25 01:52 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Data/EdFiDbQueryData.cs
> +        private string clauseConditions(ProfileSearchRequestBody body)
Please fix the naming inconsistency here. C should be uppercase.

2021-03-25 01:52 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Data/EdFiDbQueryData.cs
> +        private string clauseDegrees(ProfileSearchRequestDegrees degrees)
This looks incomplete. I know this is WIP.  There is no point in pushing incomplete code up to main.

2021-05-04 19:27 UTC, YogirajA commented
cant be merged

2021-05-04 19:27 UTC, closed without merging