Feature/lp 66 advanced search
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #47
Opened 2021-03-26 03:19 UTC by javier1martinez

2021-03-26 04:19 UTC, harveymw27 requested changes

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/components/DirectoryComponents/AdvancedSearchComponent/UseAdvancedSearch.js
> +            {
Just return an empty set. We know this needs to be modified when specialization can be resolved.

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/components/DirectoryComponents/Directory.js
> +                        {/* <span className="view-style-label">View Style</span> */}
Do not check in commented code. It creates technical debt.

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/components/DirectoryComponents/UseDirectory.js
> +        let path = '/advanced/search?page=1&sortBy=desc&sortField=id';
Set sort order to ASC as a default.

2021-03-26 04:19 UTC, harveymw27 commented on src/API/DatabaseMigrations/scripts/views/vw_ListAllSubCategories.sql
> +select null as [NotImplemented]
Since this is for edfi repo, please modify the select statement to this:

select null as [Text], null as [Value] where 10 < 1

This allows the view to return "no rows" and prevents any errors or crashes on the calling side.

2021-03-26 04:19 UTC, harveymw27 commented on src/API/DatabaseMigrations/scripts/views/vw_ListAllCategories.sql
> +select null as [NotImplemented]
Since this is for edfi repo, please modify the select statement to this:

select null as [Text], null as [Value] where 10 < 1

This allows the view to return "no rows" and prevents any errors or crashes on the calling side.

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/components/DirectoryComponents/AdvancedSearchComponent/UseSearchDirectory.js
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
If this commented code is not needed please remove it

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/components/DirectoryComponents/AdvancedSearchComponent/UseSearchDirectory.js
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
If this commented code is not needed please remove it

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/components/DirectoryComponents/AdvancedSearchComponent/UseSearchDirectory.js
> +        // eslint-disable-next-line react-hooks/exhaustive-deps
If this commented code is not needed please remove it

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/components/DirectoryComponents/AdvancedSearchComponent/SearchDirectory.js
> +                    </div> */}
If this commented code is not needed please remove it

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/App.css
> +  /* margin-bottom: 15px; */
If this commented code is not needed please remove it

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/App.css
> +  /* padding: 24px 10px; */
If this commented code is not needed please remove it

2021-03-26 04:19 UTC, harveymw27 commented on src/Web/src/components/DirectoryComponents/AdvancedSearchComponent/AdvancedSearch.js
> +        // }
If this commented code is not needed please remove it

2021-03-26 17:22 UTC, harveymw27 approved these changes

2021-05-04 19:27 UTC, YogirajA commented
Cant be merged

2021-05-04 19:27 UTC, closed without merging