Feature/lp 16 listing page development
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #5
Opened 2020-12-02 15:58 UTC by allisono-hs

- table functionality
- table UI

need to fix 
- warnings
- icons on table
- spacing of right side of nav bar

2020-12-04 17:15 UTC, YogirajA commented
1. Please fix some of the unverified commits. Let me know if you want me to flag them
2. The front end should handle errors coming from the API and display them at the message on top. The error bod looks like this. 
<img width="716" alt="ApiError" src="https://user-images.githubusercontent.com/1694302/101193159-c745e780-3621-11eb-95ec-6242446892a2.png">
3. The names are looking incorrect. It can be handled in the backend as well if that makes life easier. 
<img width="1268" alt="FirstName" src="https://user-images.githubusercontent.com/1694302/101193251-ec3a5a80-3621-11eb-8216-8fcfaf290bee.png">

2020-12-04 20:28 UTC, allisono-hs commented
Took care of issues 2-5

2020-12-07 15:54 UTC, YogirajA requested changes

2020-12-07 16:15 UTC, allisono-hs commented on src/API/LeadershiProfileAPI.Tests/ProfileControllerTests.cs
> +            var result = (await controller.GetDirectory("1",null,null,null)).Profiles.ToList();
Should we build more tests or just fix this test?

2020-12-07 16:47 UTC, allisono-hs commented on src/API/LeadershipProfileAPI/Controllers/ProfileController.cs
> +            foreach (var teacherProfile in response.response)
seperate ticket?

2020-12-07 17:12 UTC, allisono-hs commented on src/API/LeadershipProfileAPI/Controllers/Extensions.cs
> +            return address == null ? "Default Location" : $"{address.city}, {address.stateAbbreviationDescriptor.Split('#')[1]}";
with the https://api.ed-fi.org/ there's no addresses to see and test this

2020-12-07 17:43 UTC, allisono-hs commented on src/Web/.gitignore
> +# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.
done

2020-12-07 17:43 UTC, allisono-hs commented on src/Web/public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
deleted

2020-12-07 17:43 UTC, allisono-hs commented on src/Web/src/setupTests.js
> +import '@testing-library/jest-dom';
wasnt planning on it so deleting it

2020-12-07 17:44 UTC, allisono-hs commented on src/API/LeadershipProfileAPI/Controllers/ProfileController.cs
> +                    .Where(x => x.FirstName.ToLowerInvariant().Contains(search) || x.LastName.ToLowerInvariant().Contains(search))
commented out

2020-12-07 17:44 UTC, allisono-hs commented on src/API/LeadershipProfileAPI/Controllers/Models.cs
> +            [JsonPropertyName("lastSurname")] public string LastName { get; set; }
done!

2020-12-07 17:44 UTC, allisono-hs commented on src/Web/README.md
> +# Getting Started with Create React App
done!

2020-12-07 17:44 UTC, allisono-hs commented on src/Web/src/App.test.js
> +import { render, screen } from '@testing-library/react';
no, deleted

2020-12-08 16:24 UTC, YogirajA commented on src/API/LeadershiProfileAPI.Tests/ProfileControllerTests.cs
> +            var result = (await controller.GetDirectory("1",null,null,null)).Profiles.ToList();
added more tests and this test works now

2020-12-08 16:24 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Controllers/ProfileController.cs
> +            foreach (var teacherProfile in response.response)
We will address this in the future.

2020-12-08 16:33 UTC, YogirajA commented on src/API/LeadershipProfileAPI/appsettings.Development.json
> +  "Logging": {
This is good to keep.

2020-12-08 23:43 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Controllers/Extensions.cs
> +            return address == null ? "Default Location" : $"{address.city}, {address.stateAbbreviationDescriptor.Split('#')[1]}";
fixed

2020-12-08 23:43 UTC, YogirajA approved these changes

2020-12-08 23:44 UTC, merged