Advanced Search - API
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #51
Opened 2021-05-04 15:28 UTC by wooleyHeadspring

This is a manual merge from [v0.4.30-beta](https://github.com/kleinisd-lp/Leadership-Profile/releases/tag/v0.4.30-beta) in the Klein repo.  Changes were manual to ensure the commits are properly signed.  This PR includes the addition of views, controllers, models, and tests that add the "Advanced Search" functionality.

The tests included are not validating the data in the database, but rather that the contracts and queries are functionally sound.

2021-05-06 14:58 UTC, YogirajA requested changes
Besides the inline comments, please address below

- [x] Fix the failing build
- [ ] Search from swagger is giving **Conversion failed when converting date and/or time from character string** error. It needs to be fixed.

2021-05-06 14:58 UTC, YogirajA commented on src/API/LeadershipProfileAPI/Startup.cs
> +                    policy.WithOrigins(new string[] { authorityServer, webClient, "http://localhost", "https://localhost" })
I wonder why http is necessary.

2021-05-06 16:21 UTC, wooleyHeadspring commented on src/API/LeadershipProfileAPI/Controllers/ClaimCheckAttribute.cs
> +            Arguments = new object[] { claimType, claimValue };
Duly noted.  Will keep that in mind in the future.

2021-05-06 18:32 UTC, wooleyHeadspring commented on src/API/LeadershipProfileAPI/Data/Models/ListItem/ListItemCategory.cs
> +    public class ListItemCategory
Good idea. Will do that.

2021-05-06 18:34 UTC, wooleyHeadspring commented on src/API/LeadershipProfileAPI/Data/Models/ListItem/ListItemSubCategory.cs
> +    public class ListItemSubCategory
ListItemSubCategory will now derive from the same ListItemBsae

2021-05-06 18:36 UTC, wooleyHeadspring commented on src/API/LeadershipProfileAPI/Extensions/ListExtensions.cs
> +                if (!string.IsNullOrWhiteSpace(value))
This extension class will be removed as it is no longer used after cleanup of EdFiDbQueryData.GetSearchResultsAsync.

2021-05-06 18:37 UTC, wooleyHeadspring commented on src/API/LeadershipProfileAPI/Startup.cs
> +                    policy.WithOrigins(new string[] { authorityServer, webClient, "http://localhost", "https://localhost" })
The Client defaults to port 80 and there is no "HTTPS=true" on the startup scripts in [package.json](https://github.com/Ed-Fi-Exchange-OSS/Leadership-Profile/blob/e9f988db1327e3db7f3cc15134c9b737ad243603/src/Web/package.json#L23)

2021-05-06 21:11 UTC, wooleyHeadspring commented
@YogirajA, comments have been addressed from feedback and committed [here](https://github.com/Ed-Fi-Exchange-OSS/Leadership-Profile/pull/51/commits/9e505cb1fc201f8ae15c1c342776fb6fd6b725ff)

As for "Search from swagger is giving Conversion failed when converting date and/or time from character string error. It needs to be fixed.". This was addressed by changing the data type for the properties to DateTime from string.  This will throw an error, but it is much more specific on what the issue is...
{
  "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
  "title": "One or more validation errors occurred.",
  "status": 400,
  "traceId": "00-74c4c8cb7ea68f48aae759a001ef1e6b-606aa7c22b3e204b-00",
  "errors": {
    "$.certifications.issueDate": [
      "The JSON value could not be converted to System.Nullable`1[System.DateTime]. Path: $.certifications.issueDate | LineNumber: 0 | BytePositionInLine: 125."
    ]
  }
}

2021-05-07 15:24 UTC, YogirajA approved these changes

2021-05-07 15:24 UTC, merged