Advanced Search - Client
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #52
Opened 2021-05-04 15:35 UTC by wooleyHeadspring

This is a manual merge from [v0.4.30-beta](https://github.com/kleinisd-lp/Leadership-Profile/releases/tag/v0.4.30-beta) in the Klein repo.  Changes were manual to ensure the commits are properly signed.  

The changes below cover the implementation of the client for the Advanced Search UI, refactoring of common code, cleaning up card layout, and fixing various UI bugs.

2021-05-06 21:50 UTC, wooleyHeadspring commented
@YogirajA This PR has been updated to reflect the changes to the DateTime on the properties for the API.

2021-05-10 14:31 UTC, YogirajA requested changes

2021-05-10 16:18 UTC, wooleyHeadspring commented on src/Web/src/components/DirectoryComponents/AdvancedSearchComponent/AdvancedSearch.js
> +            }
Agreed. A lot of the logic in AdvancedSearch could have been refactored.  Change completed in 320328917b11bc1103039fa98ec4de4b492a2e44

2021-05-10 16:25 UTC, wooleyHeadspring commented
@YogirajA Requested changes have been implemented.

2021-05-10 18:34 UTC, merged