Replace years column by tenure column
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #79
Opened 2021-08-25 18:38 UTC by josemtzb

These are the changes:

- The Year column was replaced by the tenure column (suggested ranges were added)
- The functionality to search by one or more tenure ranges was implemented
- The changes to make the Tenure filter persist after navigating across different pages were implemented based on the changes that Gilberto did on his branch.
- The vw_StaffSearch.sql view was updated to take the YearsOfExperience value from staff.YearsOfPriorProfessionalExperience column as requested.
- ***Before merging this branch to main, this [PR](https://github.com/Ed-Fi-Exchange-OSS/Leadership-Profile/pull/77) needs to be approved. if any change is made in that branch, we need to merge it to this branch first***

2021-08-31 13:18 UTC, pmcvtm requested changes
There's some cleanup we need to do here before this can be merged:

- fix failing tests (see build results)
- remove artifacts of existing `Years` from front end, API, and query
- rename `Tenure` in API to `YearsOfPriorExperience`

2021-08-31 13:18 UTC, pmcvtm commented on src/API/LeadershipProfileAPI/Data/Models/ProfileSearchRequest/ProfileSearchRequestTenure.cs
> +    public class ProfileSearchRequestTenure
SHOULD: Rename to `ProfileSearchRequestYearsOfPriorExperience`

Even though we're calling this `Tenure` on the front-end to match the label here in the API it might make more sense to keep it aligned with the database and call it `YearsOfPriorExperience`.

2021-08-31 13:18 UTC, pmcvtm commented on src/Web/src/components/DirectoryComponents/DirectoryFilters.js
> +                "MinYears": 0,
MUST: Remove obsolete `Years` controls

2021-08-31 13:18 UTC, pmcvtm commented on src/API/LeadershipProfileAPI/Data/Models/ProfileSearchRequest/ProfileSearchRequestBody.cs
> +        public ProfileSearchRequestTenure TenureRanges { get; set; }
SHOULD: Rename

Similar to the `ProfileSearchRequestTenure` name, we should keep this in-line with the data in the back-end, and call it `YearsOfPriorExperienceRanges`

2021-09-02 18:19 UTC, josemtzb commented on src/API/DatabaseMigrations/scripts/views/vw_StaffSearch.sql
>  with staffService as (
Fixed

2021-09-02 18:19 UTC, josemtzb commented on src/API/DatabaseMigrations/scripts/views/vw_StaffSearch.sql
> +), staffYearsOfExperience as (
removed

2021-09-02 18:19 UTC, josemtzb commented on src/Web/src/components/DirectoryComponents/DirectoryFilters.js
> +            //setYearsOptionRange('-1');
removed

2021-09-02 18:19 UTC, josemtzb commented on src/Web/src/components/DirectoryComponents/DirectoryFilters.js
> +            if(typeof(tenureOptions) !=='undefined')
updated

2021-09-02 18:19 UTC, josemtzb commented on src/Web/src/components/DirectoryComponents/DirectoryFilters.js
>                              <FormGroup className="mb-2 mr-sm-2 mb-sm-0">
removed

2021-09-02 18:20 UTC, josemtzb commented on src/API/LeadershipProfileAPI/Data/Models/ProfileSearchRequest/ProfileSearchRequestTenure.cs
> +    public class ProfileSearchRequestTenure
updated

2021-09-02 18:20 UTC, josemtzb commented on src/API/LeadershipProfileAPI/Data/EdFiDbQueryData.cs
> +                    ClauseYears(body.MinYears, body.MaxYears),
removed

2021-09-02 18:20 UTC, josemtzb commented on src/Web/src/components/DirectoryComponents/DirectoryFilters.js
> +                "MinYears": 0,
removed

2021-09-02 18:20 UTC, josemtzb commented on src/API/LeadershipProfileAPI/Data/Models/ProfileSearchRequest/ProfileSearchRequestBody.cs
>          public ProfileSearchRequestInstitution Institutions { get; set; }
removed

2021-09-02 18:20 UTC, josemtzb commented on src/API/LeadershipProfileAPI/Data/Models/ProfileSearchRequest/ProfileSearchRequestBody.cs
> +        public ProfileSearchRequestTenure TenureRanges { get; set; }
updated

2021-09-02 20:31 UTC, josemtzb commented on src/Web/src/context/filters/Reducer.js
> +        case removeTenure:{
this would be reviewed once the data is correctly mapped, the duplicated data may affect how the it's displayed

2021-09-02 22:34 UTC, pmcvtm approved these changes

2021-09-02 22:36 UTC, pmcvtm commented
Fixups look good overall. Unit tests were still failing due to a missing `null` check (didn't effect manual testing since the model binding initiated the object). Did a bit of renaming / cleanup while I was in there.

Definitely something is up with the results returning, but we'll see how they are effected when moved to 1.0. We'll also be able to include the `Tenure` filter in our new tests.

2021-09-02 22:39 UTC, merged