Chart component
Ed-Fi-Exchange-OSS/Leadership-Profile pull request #85
Opened 2021-09-01 17:59 UTC by josemtzb

The chart component was created to display evaluation data

2021-09-01 19:07 UTC, pmcvtm requested changes
Overall these look great; we have a couple tweaks and some code cleanup to take care of, and then we can merge this.

2021-09-01 19:27 UTC, pmcvtm commented on src/Web/src/components/EvaluationChartComponent/EvaluationChart.js
> +                <span>Year/s </span>
SHOULD: Change to `Year`

2021-09-03 15:33 UTC, josemtzb commented on src/Web/src/components/EvaluationChartComponent/EvaluationChart.js
> +    function setTable(title) {
Removed

2021-09-03 15:33 UTC, josemtzb commented on src/Web/src/components/ProfileComponents/Profile.js
> +//import LeaderOfOrgChart from './LeaderOfOrgChart';
Removed

2021-09-03 15:34 UTC, josemtzb commented on src/Web/src/components/ProfileComponents/Profile.js
> +                    <NavLink onClick={() => setActiveComponent("leader")}>Leader or self</NavLink>
Change reverted

2021-09-03 15:34 UTC, josemtzb commented on src/Web/src/components/EvaluationChartComponent/EvaluationChart.js
> +                            maxBarThickness:36,
Fixed

2021-09-03 15:34 UTC, josemtzb commented on src/Web/src/components/EvaluationChartComponent/EvaluationChart.js
> +                <span>Year/s </span>
Updated

2021-09-03 15:35 UTC, josemtzb commented on src/Web/src/components/ProfileComponents/Profile.js
> +                        <EvaluationChart title='Overall' data={data.evaluations} />
Charts are loaded dynamically, based on the API data provided

2021-09-03 15:36 UTC, josemtzb commented on src/Web/src/components/ProfileComponents/CanvasChart.js
> +  // var periods = [];
Code restored

2021-09-03 15:58 UTC, pmcvtm approved these changes

2021-09-03 15:58 UTC, merged